### ISSUE TITLE
There are still tests with ZopeTestCase as a base class

### ISSUE THREAD

**Issue by gforcada** [plone/Products.CMFEditions#22]
```
gil@patam $ git grep ZopeTestCase
Products/CMFEditions/tests/webdav_history.txt:27:  >>> from Testing.ZopeTestCase.zopedoctest.functional import http
Products/CMFEditions/tests/webdav_history.txt:28:  >>> from Testing.ZopeTestCase.sandbox import AppZapper
```
Seems that when finally #21 was merged it was not a complete migration to p.a.testing.

Maybe this explains the isolation problems on the Plone 5 AT jenkins job that we were seeing yesterday? cc @tomgross @tisto @jensens

**Comment by tomgross** [comment]
Depending on ZopeTestCase is OK. p.a.testing does that too.

**Comment by gforcada** [comment]
Ok, sorry about that.
