### ISSUE TITLE
Edition of AT is broken

### ISSUE THREAD

**Issue by Gagaro** [plone/Products.CMFEditions#64]
Commit 275ee74d60a6fd12977eb60dde6e8586243a3ed2 breaks the edition of AT contents.

We are redirected to `update_version_before_edit` view which redirect to `view` without passing through the `content_edit` script.

**Comment by Gagaro** [comment]
cc @tdesvenain

**Comment by Gagaro** [comment]
A workaround TTW is to remove overrides in `/portal_form_controller/manage_formActionsForm`.
This removes the versioning for AT though.

**Comment by MrTango** [comment]
To fix this you have to rerun the CMFEditions profile in portal_setup.
The is an upgrade step missing in plone.app.upgrade.

**Comment by mauritsvanrees** [comment]
Fix is in plone.app.upgrade 2.0.21 from February 2019.
