### ISSUE TITLE
Replace skin with browser views and resources

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/Products.CMFEditions#72]
Next to `CMFPlone` and `CMFPlacefulWorkflow`, `CMFEditions` is the last repository on Plone 5.2 Py 3 which still has a skins directory. It seems better to replace this with browser views and resources.

Current contents:

```
# python:
checkUpToDate.py
createTestHierarchy.py
get_cmfeditions_ftests.py
migrateStorage.py
revertversion.py
saveasnewversion.py
versioning_config.py

# page templates:
diff_legend.pt
version_diff.pt
versioning_config_form.pt
versions_history.pt
versions_history_form.pt
versions_history_form.pt.metadata

# images:
versioning.gif

# css:
compare.css.dtml
```

If we do this, we would be close to being able to remove the `portal_skins` tool if we want.

This is for Plone 6.0.

**Comment by jensens** [comment]
Afixed with #81
